# Generated by Django 3.2.6 on 2021-10-20 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=50)),
                ('rack', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('type', models.CharField(max_length=250)),
                ('food_group', models.CharField(default='Undefined', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_window', models.CharField(max_length=50)),
                ('substitutions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counts.menu')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counts.item')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='products',
            field=models.ManyToManyField(through='counts.Share', to='counts.Item'),
        ),
    ]
