# Generated by Django 3.1.12 on 2021-07-08 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counts.menu')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counts.product')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='products',
            field=models.ManyToManyField(through='counts.Share', to='counts.Product'),
        ),
    ]
