# Generated by Django 3.2.6 on 2021-10-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(default='Undefined', max_length=250),
        ),
    ]
