# Generated by Django 3.2.6 on 2021-10-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counts', '0002_auto_20211020_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_add', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OutOfStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_remove', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_remove', models.CharField(max_length=10)),
                ('to_add', models.CharField(max_length=10)),
                ('ratio', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='recurrance',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='item',
            name='scale_rule',
            field=models.CharField(default='111', max_length=3),
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='substitutions',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='additions',
            field=models.ManyToManyField(to='counts.Addition'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='out',
            field=models.ManyToManyField(to='counts.OutOfStock'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='substitutions',
            field=models.ManyToManyField(to='counts.Substitution'),
        ),
    ]
