# Generated by Django 3.2.6 on 2021-11-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counts', '0004_addition_quantity_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='time_window',
            field=models.CharField(choices=[('am', 'AM'), ('pm', 'PM')], max_length=50),
        ),
    ]
