# Generated by Django 3.2.6 on 2021-11-08 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counts', '0005_alter_warehouse_time_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='to_add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counts.item'),
        ),
        migrations.AlterField(
            model_name='outofstock',
            name='to_remove',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counts.item'),
        ),
        migrations.AlterField(
            model_name='substitution',
            name='to_add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_add_set', to='counts.item'),
        ),
        migrations.AlterField(
            model_name='substitution',
            name='to_remove',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_remove_set', to='counts.item'),
        ),
    ]
