# Generated by Django 3.2.6 on 2021-11-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counts', '0007_alter_substitution_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='additions',
            field=models.ManyToManyField(blank=True, null=True, to='counts.Addition'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='out',
            field=models.ManyToManyField(blank=True, null=True, to='counts.OutOfStock'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='substitutions',
            field=models.ManyToManyField(blank=True, null=True, to='counts.Substitution'),
        ),
    ]
