# Generated by Django 3.2.6 on 2021-11-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counts', '0008_auto_20211108_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addition',
            name='quantity_rule',
        ),
        migrations.AddField(
            model_name='addition',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
