# Generated by Django 3.2.6 on 2022-04-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counts', '0011_alter_warehouse_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulled_date', models.DateField(auto_now=True)),
                ('start_date', models.DateField(blank=True, editable=False)),
                ('end_date', models.DateField(blank=True, editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='additions',
            field=models.ManyToManyField(blank=True, to='counts.Addition'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='out',
            field=models.ManyToManyField(blank=True, to='counts.OutOfStock'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='substitutions',
            field=models.ManyToManyField(blank=True, to='counts.Substitution'),
        ),
    ]
