# Generated by Django 3.1.13 on 2022-09-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20220908_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='referral_type',
            field=models.CharField(choices=[('PR', 'Priority'), ('SD', 'Secondary'), ('RF', 'Referral'), ('IN', 'Inert')], default='IN', max_length=2),
            preserve_default=False,
        ),
    ]
