# Generated by Django 3.2.6 on 2021-10-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='driver',
            field=models.CharField(default='mvickers@umich.edu', max_length=50),
            preserve_default=False,
        ),
    ]
