# Generated by Django 3.2.6 on 2021-10-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_relationshipcache_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastCacheDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
