# Generated by Django 3.2.6 on 2021-10-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_lastcachedate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastcachedate',
            options={'ordering': ['-date']},
        ),
    ]
