# Generated by Django 3.2.6 on 2021-11-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, editable=False)),
                ('time_window', models.CharField(choices=[('am', 'AM'), ('pm', 'PM')], max_length=50)),
                ('active_drivers', models.ManyToManyField(to='routes.Driver')),
            ],
        ),
    ]
