# Generated by Django 3.2.6 on 2021-11-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_depot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
