# Generated by Django 3.2.4 on 2021-06-21 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(max_length=11)),
                ('recipient', models.CharField(max_length=11)),
                ('status', models.CharField(max_length=25)),
                ('words', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='texts.words')),
            ],
        ),
    ]
