# Generated by Django 3.1.12 on 2021-07-20 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_auto_20210708_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='texts.reply'),
        ),
    ]
