# Generated by Django 3.1.12 on 2021-06-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_num', models.CharField(max_length=25)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='words',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
