# Generated by Django 3.1.12 on 2021-08-17 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0003_log_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=25)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.broadcast')),
            ],
        ),
    ]
