# Generated by Django 3.2.6 on 2021-10-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0005_auto_20210906_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillfield',
            name='broadcast',
        ),
        migrations.RemoveField(
            model_name='log',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='log',
            name='words',
        ),
        migrations.DeleteModel(
            name='Received',
        ),
        migrations.DeleteModel(
            name='FillField',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
